### ISSUE TITLE
Cleanup published containers

### ISSUE THREAD

**Issue by AtomicFS** [9elements/firmware-action#135]
While we only publish containers on merge to `main` or on release, there are still a lot of containers being published.

I think we should periodically remove old one.

We should keep containers:
- with `main` tag
- with `vX.X.X` tag (release)
- with `latest` tag
- maybe also really old containers (from before I took over development) since someone might still use them ???

Possible tools:
- [actions/delete-package-versions](https://github.com/actions/delete-package-versions)
- [SmartsquareGmbH/delete-old-packages](https://github.com/SmartsquareGmbH/delete-old-packages)

**Comment by AtomicFS** [comment]
@MDr164 what do you think?

**Comment by MDr164** [comment]
Do we currently publish containers not bound to a version? If so, could you point me to one? Otherwise I agree, we should only keep version tags and it's still early enough.

**Comment by AtomicFS** [comment]
For example [coreboot 4.19](https://github.com/9elements/firmware-action/pkgs/container/firmware-action%2Fcoreboot_4.19/versions) has 46 containers and only 2 are tagged with version and one with `main`.
