### ISSUE TITLE
UDK2017 with wrong python version

### ISSUE THREAD

**Issue by PatrickRudolph** [9elements/firmware-action#439]
**Problem:**
The udk2017 docker container is using python3:
```
$ python --version
Python 3.6.9
```

The udk2017 docker container should default to python2, since EDK2 tag `udk2017` isn't python3 compatible yet.

**Possible solution:**
Use `python-is-python2` package.

**Comment by AtomicFS** [comment]
Out of curiosity, do you know since when is edk2 compatible with python3?

**Comment by PatrickRudolph** [comment]
edksetup.sh has the following line `function SetupPython()` when it's python3 compatible

**Comment by AtomicFS** [comment]
Nice, thanks
