### ISSUE TITLE
Add possibility to stitch firmware image

### ISSUE THREAD

**Issue by PatrickRudolph** [9elements/firmware-action#78]
Currently build firmware images consists of multiple parts.
There are dependencies when integrating one build artefact into the build action of another. This blocks the build process until the first component was successfully build.
To speed up compilation build everything in parallel first and then stitch the components together.

**As example:**
* Instead of integrating EFI binaries when building EDK2, add the possibilty to insert them into the UEFI Firmware Volume later.
* Instead of integrating EDK2/Linux/some payload when compiling coreboot, add the possibility to insert them into the coreboot file system (CBFS) later.

**Comment by AtomicFS** [comment]
This sounds like a cool idea, but I have no clue how to actually do it.

**Comment by PatrickRudolph** [comment]
list of tools that might help:
- https://github.com/coreboot/coreboot/tree/main/util/ifdtool
- https://github.com/coreboot/coreboot/tree/main/util/cbfstool
- https://github.com/linuxboot/fiano
